version: '3.1'
services:
  postgres-db:
    image: postgres:12.3
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    image: ghcr.io/qmchri/fachbeate-api:latest
    user: root
    container_name: backend
    env_file:
      - .env
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres-db:5432/db
      - QUARKUS_HTTP_CORS_METHODS=*
      - QUARKUS_HTTP_CORS=true
      - QUARKUS_HTTP_CORS_ORIGINS=*
      - QUARKUS_HTTP_CORS_HEADERS=*
    depends_on:
      - postgres-db
    ports:
      - "8181:9090"
  frontend:
    image: ghcr.io/qmchri/fachbeate-web:latest
    container_name: frontend
    ports:
      - "80:80"